export const CRAWLER_MEALS = [
  "Acai Bowl",
  "Air Fryer Salmon Bites",
  "Almonds",
  "Avocado",
  "Bagel",
  "Baked Cod Plate",
  "Baked Falafel Plate",
  "Baked Lemon Herb Cod",
  "Banana",
  "Banana Smoothie",
  "Beef and Broccoli Stir Fry",
  "Beef Biryani",
  "Beef Bulgogi Bowl",
  "Beef Enchiladas",
  "Beef Fajitas",
  "Beef Kofta",
  "Beef Rendang",
  "Beef Shawarma Plate",
  "Beef Stew",
  "Beef Taco",
  "Beef Udon",
  "Bell Pepper",
  "Berry Chia Pudding",
  "Berry Smoothie",
  "Bibimbap",
  "Black Bean Burrito Bowl",
  "Black Beans (cooked)",
  "Blueberry",
  "Breakfast Burrito",
  "Broccoli",
  "Broccoli Cheddar Soup Light",
  "Broccoli Garlic Pasta",
  "Brown Rice (cooked)",
  "Burrito Bean",
  "Butter Chicken",
  "Butternut Squash Soup",
  "Cabbage",
  "Caesar Salad with Chicken",
  "Canola Oil",
  "Cappuccino",
  "Carrot",
  "Cashews",
  "Cauliflower",
  "Cauliflower Chickpea Curry",
  "Chana Masala",
  "Cheddar Cheese",
  "Cheeseburger",
  "Chia Seeds",
  "Chicken Alfredo Pasta",
  "Chicken and Broccoli Bowl",
  "Chicken and Quinoa Bowl",
  "Chicken and Rice Bowl",
  "Chicken and Veggie Soup",
  "Chicken Biryani",
  "Chicken Breast (cooked)",
  "Chicken Burger",
  "Chicken Burrito Bowl",
  "Chicken Caesar Salad",
  "Chicken Caesar Wrap",
  "Chicken Congee",
  "Chicken Curry with Rice",
  "Chicken Dumplings",
  "Chicken Enchiladas",
  "Chicken Fajitas",
  "Chicken Gyro",
  "Chicken Katsu",
  "Chicken Kebab",
  "Chicken Lentil Soup",
  "Chicken Meatball Bowl",
  "Chicken Noodle Soup",
  "Chicken Noodle Stir Fry",
  "Chicken Nuggets",
  "Chicken Parmesan",
  "Chicken Pasta Salad",
  "Chicken Pita Pocket",
  "Chicken Pot Pie",
  "Chicken Quesadilla",
  "Chicken Salad Sandwich",
  "Chicken Satay",
  "Chicken Shawarma Wrap",
  "Chicken Soba Bowl",
  "Chicken Soup",
  "Chicken Souvlaki",
  "Chicken Taco Salad",
  "Chicken Tandoori",
  "Chicken Teriyaki",
  "Chicken Thigh (cooked)",
  "Chicken Tikka Masala Light",
  "Chicken Tortilla Soup",
  "Chicken Udon Soup",
  "Chicken Yakisoba",
  "Chickpea Shawarma Bowl",
  "Chickpeas (cooked)",
  "Chocolate Milk",
  "Club Sandwich",
  "Cobb Salad",
  "Coconut Oil",
  "Corn Tortilla",
  "Cottage Cheese Fruit Bowl",
  "Couscous (cooked)",
  "Crackers",
  "Croissant",
  "Cucumber",
  "Dal Tadka",
  "Dark Chocolate",
  "Dates",
  "Edamame Sushi Bowl",
  "Egg (whole)",
  "Egg and Avocado Toast",
  "Egg White",
  "Egg White Scramble Bowl",
  "Eggplant Parmesan",
  "Energy Bar",
  "Falafel Bowl",
  "Falafel Wrap",
  "Fattoush",
  "Flax Seeds",
  "Flour Tortilla",
  "Fried Egg Sandwich",
  "Fried Rice (chicken)",
  "Fried Rice (vegetable)",
  "Fruit Salad",
  "General Tso Chicken",
  "Granola",
  "Granola Bar",
  "Greek Chicken Pita",
  "Greek Salad",
  "Greek Yogurt (plain)",
  "Greek Yogurt Bowl",
  "Greek Yogurt Fruit Parfait",
  "Green Beans",
  "Green Curry Chicken",
  "Green Smoothie",
  "Grilled Chicken Power Bowl",
  "Grilled Chicken Wrap",
  "Grilled Shrimp Bowl",
  "Grilled Shrimp Skewers",
  "Ground Beef 90/10 (cooked)",
  "Ground Turkey Lettuce Wraps",
  "Guava",
  "Hamburger",
  "Healthy Turkey Chili",
  "Homemade Chicken Noodle Soup",
  "Honey",
  "Hummus Power Plate",
  "Ice Cream (vanilla)",
  "Iced Latte",
  "Instant Pot Chicken Soup",
  "Jam",
  "Kale",
  "Kale Chicken Salad",
  "Kidney Beans (cooked)",
  "Kimchi Fried Rice",
  "Kimchi Tofu Bowl",
  "Kiwi",
  "Korean BBQ Beef",
  "Kung Pao Chicken",
  "Lamb Gyro",
  "Lasagna",
  "Lean Beef (cooked)",
  "Lemon",
  "Lemon Herb Chicken Plate",
  "Lentil Buddha Bowl",
  "Lentil Soup",
  "Lentil Tomato Soup",
  "Lentils (cooked)",
  "Lime",
  "Mango",
  "Margherita Pizza",
  "Mashed Potato",
  "Mashed Potatoes with Gravy",
  "Matcha Latte",
  "Matcha Yogurt Bowl",
  "Mayonnaise",
  "Mediterranean Chickpea Salad",
  "Mediterranean Chickpea Stew",
  "Mediterranean Grilled Salmon",
  "Mediterranean Salmon Bowl",
  "Mediterranean Tuna Bowl",
  "Mediterranean Tuna Salad",
  "Milk (whole)",
  "Milk Chocolate",
  "Milkshake (vanilla)",
  "Minestrone Soup",
  "Miso Salmon Bowl",
  "Mocha",
  "Mozzarella",
  "Muffin",
  "Mushroom",
  "Mushroom Barley Soup",
  "Oatmeal with Banana",
  "Oats (dry)",
  "Olive Oil",
  "Omelette",
  "Onion",
  "Orange Chicken",
  "Overnight Oats with Chia",
  "Palak Paneer",
  "Pancakes",
  "Paneer Tikka Bowl",
  "Papaya",
  "Pasta (cooked)",
  "Pasta Primavera",
  "Peanut Butter",
  "Peanut Butter Jelly Sandwich",
  "Peanut Butter Oatmeal Bowl",
  "Pear",
  "Peas",
  "Pepperoni Pizza",
  "Pesto Pasta",
  "Pho (beef)",
  "Pineapple",
  "Pistachios",
  "Plum",
  "Poke Bowl (chicken)",
  "Poke Bowl (salmon)",
  "Poke Bowl (tuna)",
  "Popcorn (air-popped)",
  "Pork Loin (cooked)",
  "Porridge (oatmeal milk)",
  "Potato (boiled)",
  "Potato Chips",
  "Pozole",
  "Pretzels",
  "Protein Pancakes",
  "Protein Powder",
  "Protein Yogurt Parfait",
  "Quinoa (cooked)",
  "Quinoa Salad",
  "Quinoa Tabbouleh",
  "Quinoa Veggie Salad",
  "Raisins",
  "Rajma Rice Bowl",
  "Ramen (prepared)",
  "Red Curry Tofu",
  "Rice with Chicken",
  "Risotto",
  "Roast Chicken with Potatoes",
  "Roasted Chickpea Snack Bowl",
  "Roasted Veggie Grain Bowl",
  "Salmon (cooked)",
  "Salmon and Asparagus Plate",
  "Salmon Avocado Bowl",
  "Salmon Caesar Salad",
  "Salmon Nigiri",
  "Salmon with Rice",
  "Sardine Rice Bowl",
  "Scrambled Eggs with Toast",
  "Shakshuka",
  "Shrimp (cooked)",
  "Shrimp Burrito Bowl",
  "Simple Oven-Baked Sea Bass",
  "Skim Milk",
  "Smoked Salmon Toast",
  "Smoothie (fruit)",
  "Spaghetti Bolognese",
  "Spinach",
  "Spinach Shakshuka",
  "Steak Burrito Bowl",
  "Strawberry",
  "Stuffed Zucchini Boats",
  "Sugar",
  "Sunflower Seeds",
  "Sushi (mixed)",
  "Sushi Roll (avocado)",
  "Sushi Roll (salmon)",
  "Sweet and Sour Chicken",
  "Tabbouleh",
  "Taco Beef",
  "Tempeh",
  "Teriyaki Chicken Bowl",
  "Teriyaki Tofu Bowl",
  "Thai Peanut Chicken Bowl",
  "Tikka Masala",
  "Tilapia (cooked)",
  "Toasted Sandwich",
  "Tofu (firm)",
  "Tofu and Quinoa Bowl",
  "Tofu Buddha Bowl",
  "Tofu Miso Soup",
  "Tofu Poke Bowl",
  "Tofu Stir Fry",
  "Tofu Veggie Noodle Bowl",
  "Tofu Veggie Stir-Fry",
  "Tom Yum Soup",
  "Tomato",
  "Tomato Basil Soup",
  "Tomato Soup",
  "Tonkatsu",
  "Tropical Smoothie Bowl",
  "Tuna (water)",
  "Tuna and White Bean Salad",
  "Tuna Nicoise Salad",
  "Tuna Nigiri",
  "Tuna Pasta Salad",
  "Tuna Salad Sandwich",
  "Turkey Avocado Wrap",
  "Turkey Breast (cooked)",
  "Turkey Chili",
  "Turkey Meatball Bowl",
  "Turkey Quinoa Bowl",
  "Turkey Sandwich",
  "Vegan Pancakes",
  "Vegetable Lentil Soup",
  "Vegetable Omelette",
  "Vegetable Pho Bowl",
  "Vegetable Stir Fry",
  "Veggie Hummus Wrap",
  "Waffles",
  "Walnuts",
  "Watermelon",
  "White Bread",
  "White Rice (cooked)",
  "Whole Wheat Bread",
  "Yogurt (plain)",
  "Yogurt with Granola",
  "Zucchini"
];

