-- Sync primary meal images (batch 03) — run in Supabase SQL Editor.

begin;

update public.foods f
set
  image_url = v.url,
  image_urls = '[]'::jsonb,
  photo_source = case
    when v.url ilike '%.supabase.co/%' then 'supabase-storage'
    else 'external'
  end,
  photo_attribution = case
    when v.url ilike '%unsplash.com%' then 'Unsplash'
    when v.url ilike '%.supabase.co/%' then 'supabase meals bucket'
    else 'catalog'
  end,
  image_review_status = 'approved'
from (
  values
    ('Miso Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/miso-soup.jpg'),
    ('Mocha', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mocha.jpg'),
    ('Mozzarella', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mozzarella.jpg'),
    ('Muffin', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/muffin.jpg'),
    ('Mushroom', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mushroom.jpg'),
    ('Mushroom Barley Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mushroom-barley-soup.jpg'),
    ('Noodles with Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-noodle-stir-fry.jpg'),
    ('Oatmeal with Banana', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/oatmeal-with-banana.jpg'),
    ('Oats (dry)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/oats-dry.jpg'),
    ('Olive Oil', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/olive-oil.jpg'),
    ('Omelette', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/omelette.jpg'),
    ('Onion', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/onion.jpg'),
    ('Orange', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/orange.webp'),
    ('Orange Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/orange-chicken.jpg'),
    ('Overnight Oats with Chia', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/overnight-oats-with-chia.jpg'),
    ('Pad Thai', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pad-thai.jpg'),
    ('Palak Paneer', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/palak-paneer.jpg'),
    ('Pancakes', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pancakes.jpg'),
    ('Paneer Tikka Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/paneer-tikka-bowl.jpg'),
    ('Papaya', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mango.jpg'),
    ('Parmesan', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mozzarella.jpg'),
    ('Pasta (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pasta-cooked.jpg'),
    ('Pasta Primavera', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pasta-primavera.jpg'),
    ('Peach', 'https://pub-aaa82e9851064d22b954c3ebbafc9ae6.r2.dev/legacy/masters/peach-tea-SdR1X5msJbMy5Mu8kDuag.jpg'),
    ('Peanut Butter', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/peanut-butter.jpg'),
    ('Peanut Butter Jelly Sandwich', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/peanut-butter-jelly-sandwich.jpg'),
    ('Peanut Butter Oatmeal Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/peanut-butter-oatmeal-bowl.jpg'),
    ('Pear', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pear.jpg'),
    ('Peas', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/peas.jpg'),
    ('Pepperoni Pizza', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pepperoni-pizza.png'),
    ('Pesto Pasta', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pesto-pasta.jpg'),
    ('Pho (beef)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pho-beef.jpg'),
    ('Pineapple', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pineapple.jpg'),
    ('Pistachios', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pistachios.webp'),
    ('Pizza Cheese', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/margherita-pizza.jpg'),
    ('Plum', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/plum.jpg'),
    ('Poke Bowl (chicken)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/poke-bowl-chicken.jpg'),
    ('Poke Bowl (salmon)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/poke-bowl-salmon.jpg'),
    ('Poke Bowl (tuna)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/poke-bowl-tuna.jpg'),
    ('Popcorn (air-popped)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/popcorn-air-popped.jpg'),
    ('Pork Loin (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pork-loin-cooked.webp'),
    ('Porridge (oatmeal milk)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/porridge-oatmeal-milk.jpg'),
    ('Potato (boiled)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/potato-boiled.jpg'),
    ('Potato Chips', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/potato-chips.jpg'),
    ('Pozole', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pozole.jpg'),
    ('Pretzels', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pretzels.jpg'),
    ('Protein Pancakes', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/protein-pancakes.jpg'),
    ('Protein Powder', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/protein-powder.jpg'),
    ('Protein Yogurt Parfait', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/protein-yogurt-parfait.jpg'),
    ('Quinoa (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/quinoa-cooked.jpg'),
    ('Quinoa Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/quinoa-salad.jpg'),
    ('Quinoa Tabbouleh', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/quinoa-tabbouleh.jpg'),
    ('Quinoa Veggie Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/quinoa-veggie-salad.jpg'),
    ('Raisins', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/raisins.jpg'),
    ('Rajma Rice Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/rajma-rice-bowl.jpg'),
    ('Ramen (prepared)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/ramen-prepared.jpg'),
    ('Red Curry Tofu', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/red-curry-tofu.jpg'),
    ('Rice with Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/rice-with-chicken.jpg'),
    ('Risotto', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/risotto.jpg'),
    ('Roast Chicken with Potatoes', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/roast-chicken-with-potatoes.jpg'),
    ('Roasted Chickpea Snack Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/roasted-chickpea-snack-bowl.jpg'),
    ('Roasted Turkey Plate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/roasted-turkey-plate.jpg'),
    ('Roasted Veggie Grain Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/roasted-veggie-grain-bowl.webp'),
    ('Salmon (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-cooked.jpg'),
    ('Salmon and Asparagus Plate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-and-asparagus-plate.jpg'),
    ('Salmon Avocado Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-avocado-bowl.jpg'),
    ('Salmon Caesar Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-caesar-salad.jpg'),
    ('Salmon Nigiri', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-nigiri.jpg'),
    ('Salmon with Rice', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-with-rice.jpg'),
    ('Sardine Rice Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sardine-rice-bowl.webp'),
    ('Scrambled Eggs with Toast', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/scrambled-eggs-with-toast.jpg'),
    ('Shakshuka', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/shakshuka.jpg'),
    ('Shrimp (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/shrimp-cooked.jpg'),
    ('Shrimp Burrito Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/shrimp-burrito-bowl.jpg'),
    ('Simple Oven-Baked Sea Bass', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/simple-oven-baked-sea-bass.jpg'),
    ('Skim Milk', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/skim-milk.jpg'),
    ('Smoked Salmon Toast', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/smoked-salmon-toast.jpg'),
    ('Smoothie (fruit)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/smoothie-fruit.jpg'),
    ('Spaghetti Bolognese', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/spaghetti-bolognese.jpg'),
    ('Spinach', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/spinach.jpg'),
    ('Spinach Berry Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kale-chicken-salad.jpg'),
    ('Spinach Shakshuka', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/spinach-shakshuka.jpg'),
    ('Steak Burrito Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/steak-burrito-bowl.jpg'),
    ('Steak with Rice', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-bulgogi-bowl.webp'),
    ('Strawberry', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/strawberry.jpg'),
    ('Stuffed Bell Pepper', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/stuffed-zucchini-boats.jpg'),
    ('Stuffed Zucchini Boats', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/stuffed-zucchini-boats.jpg'),
    ('Sugar', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sugar.jpg'),
    ('Sunflower Seeds', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sunflower-seeds.jpg'),
    ('Sushi (mixed)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sushi-mixed.jpg'),
    ('Sushi Roll (avocado)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sushi-roll-avocado.jpg'),
    ('Sushi Roll (salmon)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sushi-roll-salmon.jpg'),
    ('Sweet and Sour Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sweet-and-sour-chicken.jpg'),
    ('Sweet Potato', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sweet-potato.webp'),
    ('Tabbouleh', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/tabbouleh.jpg'),
    ('Taco Beef', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/taco-beef.jpg'),
    ('Tempeh', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/tempeh.jpg'),
    ('Teriyaki Chicken Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/teriyaki-chicken-bowl.jpg'),
    ('Teriyaki Tofu Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/teriyaki-tofu-bowl.jpg'),
    ('Thai Peanut Chicken Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/thai-peanut-chicken-bowl.png')
) as v(name, url)
where f.name = v.name;

commit;
