-- Auto-generated by scripts/build-food-image-link-sql.mjs
-- Project ref: qgnzcqwonmlijdvnbqjd
-- Bucket: Meals
-- Prefix: (none)
-- Local images dir: C:\Users\dat\Downloads\supabase-files
-- Matched images: 114
-- Missing images: 222

begin;

-- Clean legacy crawler-meals URLs before relinking.
update public.foods
set
  image_url = null,
  image_urls = '[]'::jsonb,
  photo_source = null,
  photo_attribution = null,
  image_review_status = 'pending'
where image_url ilike '%/crawler-meals/%';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/banana.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Banana';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/blueberry.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Blueberry';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/avocado.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Avocado';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/brown-rice-cooked.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Brown Rice (cooked)';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/couscous-cooked.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Couscous (cooked)';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/flour-tortilla.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Flour Tortilla';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-breast-cooked.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Breast (cooked)';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-thigh-cooked.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Thigh (cooked)';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-white.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Egg White';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chickpeas-cooked.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chickpeas (cooked)';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/black-beans-cooked.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Black Beans (cooked)';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/almonds.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Almonds';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-plain.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Greek Yogurt (plain)';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cheddar-cheese.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Cheddar Cheese';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Broccoli';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/carrot.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Carrot';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cucumber.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Cucumber';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bell-pepper.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Bell Pepper';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cauliflower.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Cauliflower';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cabbage.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Cabbage';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/canola-oil.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Canola Oil';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/coconut-oil.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Coconut Oil';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cashews.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Cashews';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chia-seeds.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chia Seeds';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/flax-seeds.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Flax Seeds';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-soup.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Soup';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-stew.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Stew';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-nuggets.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Nuggets';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/burrito-bean.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Burrito Bean';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-and-rice-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken and Rice Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-biryani.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Biryani';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-biryani.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Biryani';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-curry-with-rice.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Curry with Rice';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/butter-chicken.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Butter Chicken';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-alfredo-pasta.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Alfredo Pasta';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-shawarma-wrap.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Shawarma Wrap';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/caesar-salad-with-chicken.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Caesar Salad with Chicken';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-salad-sandwich.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Salad Sandwich';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/club-sandwich.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Club Sandwich';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-burger.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Burger';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cheeseburger.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Cheeseburger';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-taco.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Taco';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-quesadilla.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Quesadilla';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-dumplings.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Dumplings';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-meatballs-with-sauce.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Meatballs with Sauce';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-noodle-soup.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Noodle Soup';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-kebab.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Kebab';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/breakfast-burrito.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Breakfast Burrito';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/dark-chocolate.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Dark Chocolate';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/croissant.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Croissant';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bagel.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Bagel';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/energy-bar.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Energy Bar';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chocolate-milk.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chocolate Milk';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-tandoori.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Tandoori';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chana-masala.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chana Masala';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/dal-tadka.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Dal Tadka';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-souvlaki.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Souvlaki';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-shawarma-plate.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Shawarma Plate';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/falafel-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Falafel Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-caesar-wrap.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Caesar Wrap';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/avocado-toast.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Avocado Toast';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-fajitas.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Fajitas';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-fajitas.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Fajitas';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-enchiladas.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Enchiladas';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-enchiladas.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Enchiladas';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-tortilla-soup.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Tortilla Soup';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bibimbap.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Bibimbap';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-teriyaki.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Teriyaki';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-bulgogi-bowl.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Bulgogi Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-satay.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Satay';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-rendang.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Rendang';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/green-curry-chicken.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Green Curry Chicken';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-parmesan.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Parmesan';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/eggplant-parmesan.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Eggplant Parmesan';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-noodle-stir-fry.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Noodle Stir Fry';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-pot-pie.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Pot Pie';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-burrito-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Burrito Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-gyro.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Gyro';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-kofta.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Kofta';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-katsu.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Katsu';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-yakisoba.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Yakisoba';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-udon.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef Udon';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-congee.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Congee';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-and-quinoa-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken and Quinoa Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-caesar-salad.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Caesar Salad';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-pita-pocket.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Pita Pocket';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/banana-smoothie.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Banana Smoothie';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/berry-smoothie.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Berry Smoothie';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cappuccino.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Cappuccino';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/acai-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Acai Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-pasta-salad.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Pasta Salad';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-and-veggie-soup.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken and Veggie Soup';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chickpea-shawarma-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chickpea Shawarma Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-taco-salad.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Taco Salad';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/black-bean-burrito-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Black Bean Burrito Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-chicken-pita.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Greek Chicken Pita';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-soba-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Soba Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-udon-soup.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Udon Soup';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-cod-plate.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Baked Cod Plate';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-meatball-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Meatball Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-falafel-plate.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Baked Falafel Plate';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-lentil-soup.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Lentil Soup';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/butternut-squash-soup.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Butternut Squash Soup';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-white-scramble-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Egg White Scramble Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/berry-chia-pudding.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Berry Chia Pudding';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-and-broccoli-bowl.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken and Broccoli Bowl';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli-cheddar-soup-light.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Broccoli Cheddar Soup Light';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-and-broccoli-stir-fry.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Beef and Broccoli Stir Fry';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli-garlic-pasta.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Broccoli Garlic Pasta';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-tikka-masala-light.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Chicken Tikka Masala Light';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-lemon-herb-cod.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Baked Lemon Herb Cod';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-fruit-parfait.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Greek Yogurt Fruit Parfait';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/air-fryer-salmon-bites.jpg',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Air Fryer Salmon Bites';

update public.foods
set
  image_url = 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cauliflower-chickpea-curry.webp',
  image_urls = '[]'::jsonb,
  photo_source = 'supabase-storage',
  photo_attribution = 'supabase meals upload',
  image_review_status = 'approved'
where name = 'Cauliflower Chickpea Curry';

commit;

-- Missing meals (no local downloaded image found):
-- Apple
-- Orange
-- Strawberry
-- Pineapple
-- Mango
-- Watermelon
-- Pear
-- Kiwi
-- Plum
-- Papaya
-- Guava
-- Dates
-- Raisins
-- Lemon
-- Lime
-- White Rice (cooked)
-- Quinoa (cooked)
-- Oats (dry)
-- Whole Wheat Bread
-- White Bread
-- Pasta (cooked)
-- Corn Tortilla
-- Sweet Potato
-- Potato (boiled)
-- Mashed Potato
-- French Fries
-- Popcorn (air-popped)
-- Turkey Breast (cooked)
-- Lean Beef (cooked)
-- Ground Beef 90/10 (cooked)
-- Pork Loin (cooked)
-- Salmon (cooked)
-- Tuna (water)
-- Tilapia (cooked)
-- Shrimp (cooked)
-- Egg (whole)
-- Tofu (firm)
-- Tempeh
-- Lentils (cooked)
-- Kidney Beans (cooked)
-- Peanut Butter
-- Milk (whole)
-- Milk (2%)
-- Skim Milk
-- Yogurt (plain)
-- Cottage Cheese
-- Mozzarella
-- Parmesan
-- Spinach
-- Kale
-- Tomato
-- Onion
-- Mushroom
-- Zucchini
-- Green Beans
-- Peas
-- Olive Oil
-- Mayonnaise
-- Walnuts
-- Pistachios
-- Sunflower Seeds
-- Pizza Cheese
-- Hamburger
-- Hot Dog
-- Fried Chicken
-- Sushi (mixed)
-- Ramen (prepared)
-- Taco Beef
-- Mac and Cheese
-- Pancakes
-- Waffles
-- Omelette
-- Rice with Chicken
-- Tikka Masala
-- Fried Rice (chicken)
-- Fried Rice (vegetable)
-- Spaghetti Bolognese
-- Lasagna
-- Grilled Chicken Wrap
-- Falafel Wrap
-- Greek Salad
-- Sushi Roll (salmon)
-- Sushi Roll (avocado)
-- Pad Thai
-- Pho (beef)
-- Lentil Soup
-- Tomato Soup
-- Mashed Potatoes with Gravy
-- Roast Chicken with Potatoes
-- Steak with Rice
-- Salmon with Rice
-- Teriyaki Chicken Bowl
-- Poke Bowl (salmon)
-- Poke Bowl (tuna)
-- Scrambled Eggs with Toast
-- Oatmeal with Banana
-- Yogurt with Granola
-- Fried Egg Sandwich
-- Sugar
-- Honey
-- Jam
-- Milk Chocolate
-- Granola
-- Protein Powder
-- Toasted Sandwich
-- Muffin
-- Ice Cream (vanilla)
-- Potato Chips
-- Pretzels
-- Crackers
-- Granola Bar
-- Peanut Butter Jelly Sandwich
-- Milkshake (vanilla)
-- Smoothie (fruit)
-- Shakshuka
-- Palak Paneer
-- Turkey Sandwich
-- Tuna Salad Sandwich
-- Pozole
-- Korean BBQ Beef
-- Kimchi Fried Rice
-- Miso Soup
-- General Tso Chicken
-- Orange Chicken
-- Kung Pao Chicken
-- Sweet and Sour Chicken
-- Tom Yum Soup
-- Red Curry Tofu
-- Pasta Primavera
-- Minestrone Soup
-- Risotto
-- Margherita Pizza
-- Pepperoni Pizza
-- Pesto Pasta
-- Vegetable Stir Fry
-- Tofu Stir Fry
-- Turkey Chili
-- Steak Burrito Bowl
-- Shrimp Burrito Bowl
-- Lamb Gyro
-- Tonkatsu
-- Salmon Nigiri
-- Tuna Nigiri
-- Porridge (oatmeal milk)
-- Greek Yogurt Bowl
-- Fruit Salad
-- Tofu and Quinoa Bowl
-- Poke Bowl (chicken)
-- Quinoa Salad
-- Tabbouleh
-- Fattoush
-- Vegetable Omelette
-- Egg and Avocado Toast
-- Protein Pancakes
-- Green Smoothie
-- Iced Latte
-- Mocha
-- Matcha Latte
-- Tuna Pasta Salad
-- Cobb Salad
-- Mediterranean Salmon Bowl
-- Grilled Chicken Power Bowl
-- Turkey Quinoa Bowl
-- Lentil Buddha Bowl
-- Roasted Veggie Grain Bowl
-- Tofu Buddha Bowl
-- Grilled Shrimp Bowl
-- Mediterranean Chickpea Salad
-- Tuna Nicoise Salad
-- Salmon Caesar Salad
-- Spinach Berry Salad
-- Kale Chicken Salad
-- Quinoa Tabbouleh
-- Veggie Hummus Wrap
-- Turkey Avocado Wrap
-- Salmon Avocado Bowl
-- Tofu Poke Bowl
-- Edamame Sushi Bowl
-- Miso Salmon Bowl
-- Thai Peanut Chicken Bowl
-- Teriyaki Tofu Bowl
-- Vegetable Pho Bowl
-- Tofu Miso Soup
-- Sardine Rice Bowl
-- Kimchi Tofu Bowl
-- Paneer Tikka Bowl
-- Rajma Rice Bowl
-- Lemon Herb Chicken Plate
-- Roasted Turkey Plate
-- Stuffed Bell Pepper
-- Turkey Meatball Bowl
-- Hummus Power Plate
-- Vegetable Lentil Soup
-- Tomato Basil Soup
-- Mushroom Barley Soup
-- Overnight Oats with Chia
-- Protein Yogurt Parfait
-- Smoked Salmon Toast
-- Peanut Butter Oatmeal Bowl
-- Tropical Smoothie Bowl
-- Matcha Yogurt Bowl
-- Salmon and Asparagus Plate
-- Tuna and White Bean Salad
-- Tofu Veggie Noodle Bowl
-- Cottage Cheese Fruit Bowl
-- Mediterranean Tuna Bowl
-- Roasted Chickpea Snack Bowl
-- Homemade Chicken Noodle Soup
-- Mediterranean Chickpea Stew
-- Mediterranean Grilled Salmon
-- Healthy Turkey Chili
-- Simple Oven-Baked Sea Bass
-- Vegan Pancakes
-- Spinach Shakshuka
-- Grilled Shrimp Skewers
-- Lentil Tomato Soup
-- Quinoa Veggie Salad
-- Tofu Veggie Stir-Fry
-- Instant Pot Chicken Soup
-- Ground Turkey Lettuce Wraps
-- Mediterranean Tuna Salad
-- Stuffed Zucchini Boats