-- Sync primary meal images (batch 02) — run in Supabase SQL Editor.

begin;

update public.foods f
set
  image_url = v.url,
  image_urls = '[]'::jsonb,
  photo_source = case
    when v.url ilike '%.supabase.co/%' then 'supabase-storage'
    else 'external'
  end,
  photo_attribution = case
    when v.url ilike '%unsplash.com%' then 'Unsplash'
    when v.url ilike '%.supabase.co/%' then 'supabase meals bucket'
    else 'catalog'
  end,
  image_review_status = 'approved'
from (
  values
    ('Chocolate Milk', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chocolate-milk.jpg'),
    ('Club Sandwich', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/club-sandwich.webp'),
    ('Cobb Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cobb-salad.jpg'),
    ('Coconut Oil', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/coconut-oil.png'),
    ('Corn Tortilla', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/corn-tortilla.jpg'),
    ('Cottage Cheese', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-plain.jpg'),
    ('Cottage Cheese Fruit Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cottage-cheese-fruit-bowl.webp'),
    ('Couscous (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/couscous-cooked.jpg'),
    ('Crackers', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/crackers.webp'),
    ('Croissant', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/croissant.jpg'),
    ('Cucumber', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cucumber.jpg'),
    ('Dal Tadka', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/dal-tadka.jpg'),
    ('Dark Chocolate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/dark-chocolate.jpg'),
    ('Dates', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/dates.jpg'),
    ('Edamame Sushi Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/edamame-sushi-bowl.jpg'),
    ('Egg (whole)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-whole.webp'),
    ('Egg and Avocado Toast', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-and-avocado-toast.jpg'),
    ('Egg White', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-white.jpg'),
    ('Egg White Scramble Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-white-scramble-bowl.jpg'),
    ('Eggplant Parmesan', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/eggplant-parmesan.jpg'),
    ('Energy Bar', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/energy-bar.jpg'),
    ('Falafel Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/falafel-bowl.jpg'),
    ('Falafel Wrap', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/falafel-wrap.jpg'),
    ('Fattoush', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fattoush.jpg'),
    ('Flax Seeds', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/flax-seeds.jpg'),
    ('Flour Tortilla', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/flour-tortilla.webp'),
    ('French Fries', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/french-fries.jpg'),
    ('Fried Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fried-chicken.jpg'),
    ('Fried Egg Sandwich', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fried-egg-sandwich.jpg'),
    ('Fried Rice (chicken)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fried-rice-chicken.jpg'),
    ('Fried Rice (vegetable)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fried-rice-vegetable.jpg'),
    ('Fruit Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fruit-salad.jpg'),
    ('General Tso Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/general-tso-chicken.jpg'),
    ('Granola', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/granola.jpg'),
    ('Granola Bar', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/granola-bar.jpg'),
    ('Grapes', 'https://pub-aaa82e9851064d22b954c3ebbafc9ae6.r2.dev/legacy/masters/fresh-grapes-in-paper-boxes-D1B7vga-3Z_u-LBueEj52.jpg'),
    ('Greek Chicken Pita', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-chicken-pita.jpg'),
    ('Greek Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-salad.jpg'),
    ('Greek Yogurt (plain)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-plain.jpg'),
    ('Greek Yogurt Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-bowl.jpg'),
    ('Greek Yogurt Fruit Parfait', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-fruit-parfait.jpg'),
    ('Green Beans', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/green-beans.jpg'),
    ('Green Curry Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/green-curry-chicken.jpg'),
    ('Green Smoothie', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/green-smoothie.jpg'),
    ('Grilled Chicken Power Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/grilled-chicken-power-bowl.jpg'),
    ('Grilled Chicken Wrap', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/grilled-chicken-wrap.jpg'),
    ('Grilled Shrimp Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/grilled-shrimp-bowl.jpg'),
    ('Grilled Shrimp Skewers', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/grilled-shrimp-skewers.jpg'),
    ('Ground Beef 90/10 (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/ground-beef-90-10-cooked.jpg'),
    ('Ground Turkey Lettuce Wraps', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/ground-turkey-lettuce-wraps.jpg'),
    ('Guava', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/guava.jpg'),
    ('Hamburger', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/hamburger.webp'),
    ('Healthy Turkey Chili', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/healthy-turkey-chili.jpg'),
    ('Homemade Chicken Noodle Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/homemade-chicken-noodle-soup.jpg'),
    ('Honey', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/honey.jpg'),
    ('Hot Dog', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/hot-dog.webp'),
    ('Hummus Power Plate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/hummus-power-plate.jpg'),
    ('Hummus with Pita', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/hummus-power-plate.jpg'),
    ('Ice Cream (vanilla)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/ice-cream-vanilla.jpg'),
    ('Iced Latte', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/iced-latte.jpg'),
    ('Instant Pot Chicken Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/instant-pot-chicken-soup.jpg'),
    ('Jam', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/jam.jpg'),
    ('Kale', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kale.jpg'),
    ('Kale Chicken Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kale-chicken-salad.jpg'),
    ('Kidney Beans (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kidney-beans-cooked.jpg'),
    ('Kimchi Fried Rice', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kimchi-fried-rice.jpg'),
    ('Kimchi Tofu Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kimchi-tofu-bowl.jpg'),
    ('Kiwi', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kiwi.jpg'),
    ('Korean BBQ Beef', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/korean-bbq-beef.jpg'),
    ('Kung Pao Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kung-pao-chicken.jpg'),
    ('Lamb Gyro', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lamb-gyro.jpg'),
    ('Lasagna', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lasagna.jpg'),
    ('Lean Beef (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lean-beef-cooked.jpg'),
    ('Lemon', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lemon.jpg'),
    ('Lemon Herb Chicken Plate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lemon-herb-chicken-plate.jpg'),
    ('Lentil Buddha Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lentil-buddha-bowl.jpg'),
    ('Lentil Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lentil-soup.jpg'),
    ('Lentil Tomato Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lentil-tomato-soup.jpg'),
    ('Lentils (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lentils-cooked.jpg'),
    ('Lime', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lime.jpg'),
    ('Mac and Cheese', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mac-and-cheese.webp'),
    ('Mango', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mango.jpg'),
    ('Margherita Pizza', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/margherita-pizza.jpg'),
    ('Mashed Potato', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mashed-potato.jpg'),
    ('Mashed Potatoes with Gravy', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mashed-potatoes-with-gravy.jpg'),
    ('Matcha Latte', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/matcha-latte.jpg'),
    ('Matcha Yogurt Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/matcha-yogurt-bowl.jpg'),
    ('Mayonnaise', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mayonnaise.jpg'),
    ('Mediterranean Chickpea Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-chickpea-salad.jpg'),
    ('Mediterranean Chickpea Stew', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-chickpea-stew.jpg'),
    ('Mediterranean Grilled Salmon', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-grilled-salmon.jpg'),
    ('Mediterranean Salmon Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-salmon-bowl.jpg'),
    ('Mediterranean Tuna Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-tuna-bowl.jpg'),
    ('Mediterranean Tuna Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-tuna-salad.jpg'),
    ('Milk (2%)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/milk-2.webp'),
    ('Milk (whole)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/milk-whole.jpg'),
    ('Milk Chocolate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/milk-chocolate.jpg'),
    ('Milkshake (vanilla)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/milkshake-vanilla.jpg'),
    ('Minestrone Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/minestrone-soup.jpg'),
    ('Miso Salmon Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/miso-salmon-bowl.jpg')
) as v(name, url)
where f.name = v.name;

commit;
