-- Sync primary meal images (batch 01) — run in Supabase SQL Editor.
-- Matches foods by exact `name`; clears duplicate alternates.

begin;

update public.foods f
set
  image_url = v.url,
  image_urls = '[]'::jsonb,
  photo_source = case
    when v.url ilike '%.supabase.co/%' then 'supabase-storage'
    else 'external'
  end,
  photo_attribution = case
    when v.url ilike '%unsplash.com%' then 'Unsplash'
    when v.url ilike '%.supabase.co/%' then 'supabase meals bucket'
    else 'catalog'
  end,
  image_review_status = 'approved'
from (
  values
    ('Acai Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/acai-bowl.jpg'),
    ('Air Fryer Salmon Bites', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/air-fryer-salmon-bites.jpg'),
    ('Almonds', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/almonds.webp'),
    ('Apple', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/apple-v2.webp'),
    ('Asparagus', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/asparagus.webp'),
    ('Avocado', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/avocado.webp'),
    ('Avocado Toast', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/avocado-toast.webp'),
    ('Bagel', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bagel.jpg'),
    ('Baked Cod Plate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-cod-plate.jpg'),
    ('Baked Falafel Plate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-falafel-plate.jpg'),
    ('Baked Lemon Herb Cod', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-lemon-herb-cod.webp'),
    ('Banana', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/banana.webp'),
    ('Banana Smoothie', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/banana-smoothie.jpg'),
    ('Beef and Broccoli Stir Fry', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-and-broccoli-stir-fry.jpg'),
    ('Beef Biryani', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-biryani.webp'),
    ('Beef Bulgogi Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-bulgogi-bowl.webp'),
    ('Beef Burrito', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/burrito-bean.jpg'),
    ('Beef Chili', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-stew.jpg'),
    ('Beef Enchiladas', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-enchiladas.webp'),
    ('Beef Fajitas', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-fajitas.jpg'),
    ('Beef Kofta', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-kofta.jpg'),
    ('Beef Meatballs with Sauce', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-meatballs-with-sauce.webp'),
    ('Beef Rendang', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-rendang.jpg'),
    ('Beef Shawarma Plate', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-shawarma-plate.jpg'),
    ('Beef Stew', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-stew.jpg'),
    ('Beef Taco', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-taco.jpg'),
    ('Beef Udon', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-udon.webp'),
    ('Bell Pepper', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bell-pepper.webp'),
    ('Berry Chia Pudding', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/berry-chia-pudding.png'),
    ('Berry Smoothie', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/berry-smoothie.jpg'),
    ('Bibimbap', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bibimbap.jpg'),
    ('Black Bean Burrito Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/black-bean-burrito-bowl.jpg'),
    ('Black Beans (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/black-beans-cooked.jpg'),
    ('Blueberry', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/blueberry.jpg'),
    ('Breakfast Burrito', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/breakfast-burrito.jpg'),
    ('Broccoli', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli.jpg'),
    ('Broccoli Cheddar Soup Light', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli-cheddar-soup-light.jpg'),
    ('Broccoli Garlic Pasta', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli-garlic-pasta.jpg'),
    ('Brown Rice (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/brown-rice-cooked.jpg'),
    ('Burrito Bean', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/burrito-bean.jpg'),
    ('Butter', 'https://pub-aaa82e9851064d22b954c3ebbafc9ae6.r2.dev/legacy/masters/close-up-of-butter-chicken-indian-dish-IEJXHCdKkqp4aXh0Axnwi.jpg'),
    ('Butter Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/butter-chicken.jpg'),
    ('Butternut Squash Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/butternut-squash-soup.jpg'),
    ('Cabbage', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cabbage.jpg'),
    ('Caesar Salad with Chicken', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/caesar-salad-with-chicken.webp'),
    ('Canola Oil', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/canola-oil.png'),
    ('Cappuccino', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cappuccino.webp'),
    ('Carrot', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/carrot.webp'),
    ('Cashews', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cashews.jpg'),
    ('Cauliflower', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cauliflower.jpg'),
    ('Cauliflower Chickpea Curry', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cauliflower-chickpea-curry.webp'),
    ('Chana Masala', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chana-masala.jpg'),
    ('Cheddar Cheese', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cheddar-cheese.jpg'),
    ('Cheeseburger', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cheeseburger.webp'),
    ('Chia Seeds', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chia-seeds.jpg'),
    ('Chicken Alfredo Pasta', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-alfredo-pasta.jpg'),
    ('Chicken and Broccoli Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-and-broccoli-bowl.jpg'),
    ('Chicken and Quinoa Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-and-quinoa-bowl.jpg'),
    ('Chicken and Rice Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-and-rice-bowl.jpg'),
    ('Chicken and Veggie Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-and-veggie-soup.jpg'),
    ('Chicken Biryani', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-biryani.webp'),
    ('Chicken Breast (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-breast-cooked.jpg'),
    ('Chicken Burger', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-burger.jpg'),
    ('Chicken Burrito Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-burrito-bowl.jpg'),
    ('Chicken Caesar Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-caesar-salad.jpg'),
    ('Chicken Caesar Wrap', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-caesar-wrap.jpg'),
    ('Chicken Congee', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-congee.jpg'),
    ('Chicken Curry with Rice', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-curry-with-rice.jpg'),
    ('Chicken Dumplings', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-dumplings.jpg'),
    ('Chicken Enchiladas', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-enchiladas.jpg'),
    ('Chicken Fajitas', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-fajitas.jpg'),
    ('Chicken Gyro', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-gyro.jpg'),
    ('Chicken Katsu', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-katsu.jpg'),
    ('Chicken Kebab', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-kebab.jpg'),
    ('Chicken Lentil Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-lentil-soup.jpg'),
    ('Chicken Meatball Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-meatball-bowl.jpg'),
    ('Chicken Noodle Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-noodle-soup.jpg'),
    ('Chicken Noodle Stir Fry', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-noodle-stir-fry.jpg'),
    ('Chicken Nuggets', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-nuggets.jpg'),
    ('Chicken Parmesan', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-parmesan.jpg'),
    ('Chicken Pasta Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-pasta-salad.jpg'),
    ('Chicken Pita Pocket', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-pita-pocket.jpg'),
    ('Chicken Pot Pie', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-pot-pie.jpg'),
    ('Chicken Quesadilla', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-quesadilla.jpg'),
    ('Chicken Salad Sandwich', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-salad-sandwich.jpg'),
    ('Chicken Satay', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-satay.jpg'),
    ('Chicken Shawarma Wrap', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-shawarma-wrap.jpg'),
    ('Chicken Soba Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-soba-bowl.jpg'),
    ('Chicken Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-soup.jpg'),
    ('Chicken Souvlaki', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-souvlaki.jpg'),
    ('Chicken Taco Salad', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-taco-salad.jpg'),
    ('Chicken Tandoori', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-tandoori.jpg'),
    ('Chicken Teriyaki', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-teriyaki.jpg'),
    ('Chicken Thigh (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-thigh-cooked.jpg'),
    ('Chicken Tikka Masala Light', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-tikka-masala-light.jpg'),
    ('Chicken Tortilla Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-tortilla-soup.jpg'),
    ('Chicken Udon Soup', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-udon-soup.jpg'),
    ('Chicken Yakisoba', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chicken-yakisoba.png'),
    ('Chickpea Shawarma Bowl', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chickpea-shawarma-bowl.jpg'),
    ('Chickpeas (cooked)', 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chickpeas-cooked.jpg')
) as v(name, url)
where f.name = v.name;

commit;
