-- patch_fix_wrong_image_urls.sql
-- All food images now come from Supabase Storage only.
-- This file is intentionally left empty — Unsplash overrides are no longer needed.
-- To fix a food's image, update the row directly via food_image_urls_batch_*.sql.
