-- Apply pasted meal image URLs into public.foods
-- Usage:
-- 1) Replace the JSON inside payload(raw_json) with your full pasted array(s).
-- 2) Run this file in Supabase SQL Editor.
-- 3) Verify with: select name, image_url from public.foods where image_url is not null order by name;

with payload(raw_json) as (
  values (
    $$[
  { "name": "Acai Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/acai-bowl.jpg" },
  { "name": "Air Fryer Salmon Bites", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/air-fryer-salmon-bites.jpg" },
  { "name": "Almonds", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/almonds.webp" },
  { "name": "Apple", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/apple-v2.webp" },
  { "name": "Asparagus", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/asparagus.webp" },
  { "name": "Avocado", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/avocado.webp" },
  { "name": "Avocado Toast", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/avocado-toast.webp" },
  { "name": "Bagel", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bagel.jpg" },
  { "name": "Baked Cod Plate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-cod-plate.jpg" },
  { "name": "Baked Falafel Plate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-falafel-plate.jpg" },
  { "name": "Baked Lemon Herb Cod", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/baked-lemon-herb-cod.webp" },
  { "name": "Banana", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/banana.webp" },
  { "name": "Banana Smoothie", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/banana-smoothie.jpg" },
  { "name": "Beef and Broccoli Stir Fry", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-and-broccoli-stir-fry.jpg" },
  { "name": "Beef Biryani", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-biryani.webp" },
  { "name": "Beef Bulgogi Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-bulgogi-bowl.webp" },
  { "name": "Beef Burrito", "url": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80" },
  { "name": "Beef Chili", "url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80" },
  { "name": "Beef Enchiladas", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-enchiladas.webp" },
  { "name": "Beef Fajitas", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-fajitas.jpg" },
  { "name": "Beef Kofta", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-kofta.jpg" },
  { "name": "Beef Meatballs with Sauce", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-meatballs-with-sauce.webp" },
  { "name": "Beef Rendang", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-rendang.jpg" },
  { "name": "Beef Shawarma Plate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-shawarma-plate.jpg" },
  { "name": "Beef Stew", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-stew.jpg" },
  { "name": "Beef Taco", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-taco.jpg" },
  { "name": "Beef Udon", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-udon.webp" },
  { "name": "Bell Pepper", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bell-pepper.webp" },
  { "name": "Berry Chia Pudding", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/berry-chia-pudding.png" },
  { "name": "Berry Smoothie", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/berry-smoothie.jpg" },
  { "name": "Bibimbap", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/bibimbap.jpg" },
  { "name": "Black Bean Burrito Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/black-bean-burrito-bowl.jpg" },
  { "name": "Black Beans (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/black-beans-cooked.jpg" },
  { "name": "Blueberry", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/blueberry.jpg" },
  { "name": "Breakfast Burrito", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/breakfast-burrito.jpg" },
  { "name": "Broccoli", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli.jpg" },
  { "name": "Broccoli Cheddar Soup Light", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli-cheddar-soup-light.jpg" },
  { "name": "Broccoli Garlic Pasta", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/broccoli-garlic-pasta.jpg" },
  { "name": "Brown Rice (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/brown-rice-cooked.jpg" },
  { "name": "Burrito Bean", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/burrito-bean.jpg" },
  { "name": "Butter", "url": "https://pub-aaa82e9851064d22b954c3ebbafc9ae6.r2.dev/legacy/masters/close-up-of-butter-chicken-indian-dish-IEJXHCdKkqp4aXh0Axnwi.jpg" },
  { "name": "Butter Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/butter-chicken.jpg" },
  { "name": "Butternut Squash Soup", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/butternut-squash-soup.jpg" },
  { "name": "Cabbage", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cabbage.jpg" },
  { "name": "Caesar Salad with Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/caesar-salad-with-chicken.webp" },
  { "name": "Canola Oil", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/canola-oil.png" },
  { "name": "Cappuccino", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cappuccino.webp" },
  { "name": "Carrot", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/carrot.webp" },
  { "name": "Cashews", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cashews.jpg" },
  { "name": "Cauliflower", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cauliflower.jpg" },
  { "name": "Cauliflower Chickpea Curry", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cauliflower-chickpea-curry.webp" },
  { "name": "Chana Masala", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chana-masala.jpg" },
  { "name": "Chocolate Milk", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/chocolate-milk.jpg" },
  { "name": "Club Sandwich", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/club-sandwich.webp" },
  { "name": "Cobb Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cobb-salad.jpg" },
  { "name": "Coconut Oil", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/coconut-oil.png" },
  { "name": "Corn Tortilla", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/corn-tortilla.jpg" },
  { "name": "Cottage Cheese", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-plain.jpg" },
  { "name": "Cottage Cheese Fruit Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cottage-cheese-fruit-bowl.webp" },
  { "name": "Couscous (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/couscous-cooked.jpg" },
  { "name": "Crackers", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/crackers.webp" },
  { "name": "Croissant", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/croissant.jpg" },
  { "name": "Cucumber", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/cucumber.jpg" },
  { "name": "Dal Tadka", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/dal-tadka.jpg" },
  { "name": "Dark Chocolate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/dark-chocolate.jpg" },
  { "name": "Dates", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/dates.jpg" },
  { "name": "Edamame Sushi Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/edamame-sushi-bowl.jpg" },
  { "name": "Egg (whole)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-whole.webp" },
  { "name": "Egg and Avocado Toast", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-and-avocado-toast.jpg" },
  { "name": "Egg White", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-white.jpg" },
  { "name": "Egg White Scramble Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/egg-white-scramble-bowl.jpg" },
  { "name": "Eggplant Parmesan", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/eggplant-parmesan.jpg" },
  { "name": "Energy Bar", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/energy-bar.jpg" },
  { "name": "Falafel Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/falafel-bowl.jpg" },
  { "name": "Falafel Wrap", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/falafel-wrap.jpg" },
  { "name": "Fattoush", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fattoush.jpg" },
  { "name": "Flax Seeds", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/flax-seeds.jpg" },
  { "name": "Flour Tortilla", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/flour-tortilla.webp" },
  { "name": "French Fries", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/french-fries.jpg" },
  { "name": "Fried Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fried-chicken.jpg" },
  { "name": "Fried Egg Sandwich", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fried-egg-sandwich.jpg" },
  { "name": "Fried Rice (chicken)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fried-rice-chicken.jpg" },
  { "name": "Fried Rice (vegetable)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fried-rice-vegetable.jpg" },
  { "name": "Fruit Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/fruit-salad.jpg" },
  { "name": "General Tso Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/general-tso-chicken.jpg" },
  { "name": "Granola", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/granola.jpg" },
  { "name": "Granola Bar", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/granola-bar.jpg" },
  { "name": "Grapes", "url": "https://pub-aaa82e9851064d22b954c3ebbafc9ae6.r2.dev/legacy/masters/fresh-grapes-in-paper-boxes-D1B7vga-3Z_u-LBueEj52.jpg" },
  { "name": "Greek Chicken Pita", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-chicken-pita.jpg" },
  { "name": "Greek Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-salad.jpg" },
  { "name": "Greek Yogurt (plain)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-plain.jpg" },
  { "name": "Greek Yogurt Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-bowl.jpg" },
  { "name": "Greek Yogurt Fruit Parfait", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/greek-yogurt-fruit-parfait.jpg" },
  { "name": "Green Beans", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/green-beans.jpg" },
  { "name": "Green Curry Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/green-curry-chicken.jpg" },
  { "name": "Green Smoothie", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/green-smoothie.jpg" },
  { "name": "Grilled Chicken Power Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/grilled-chicken-power-bowl.jpg" },
  { "name": "Grilled Chicken Wrap", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/grilled-chicken-wrap.jpg" },
  { "name": "Grilled Shrimp Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/grilled-shrimp-bowl.jpg" },
  { "name": "Grilled Shrimp Skewers", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/grilled-shrimp-skewers.jpg" },
  { "name": "Ground Beef 90/10 (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/ground-beef-90-10-cooked.jpg" },
  { "name": "Ground Turkey Lettuce Wraps", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/ground-turkey-lettuce-wraps.jpg" },
  { "name": "Guava", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/guava.jpg" },
  { "name": "Hamburger", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/hamburger.webp" },
  { "name": "Healthy Turkey Chili", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/healthy-turkey-chili.jpg" },
  { "name": "Homemade Chicken Noodle Soup", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/homemade-chicken-noodle-soup.jpg" },
  { "name": "Honey", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/honey.jpg" },
  { "name": "Hot Dog", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/hot-dog.webp" },
  { "name": "Hummus Power Plate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/hummus-power-plate.jpg" },
  { "name": "Hummus with Pita", "url": "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=1200&q=80" },
  { "name": "Ice Cream (vanilla)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/ice-cream-vanilla.jpg" },
  { "name": "Iced Latte", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/iced-latte.jpg" },
  { "name": "Instant Pot Chicken Soup", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/instant-pot-chicken-soup.jpg" },
  { "name": "Jam", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/jam.jpg" },
  { "name": "Kale", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kale.jpg" },
  { "name": "Kale Chicken Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kale-chicken-salad.jpg" },
  { "name": "Kidney Beans (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kidney-beans-cooked.jpg" },
  { "name": "Kimchi Fried Rice", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kimchi-fried-rice.jpg" },
  { "name": "Kimchi Tofu Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kimchi-tofu-bowl.jpg" },
  { "name": "Kiwi", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kiwi.jpg" },
  { "name": "Korean BBQ Beef", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/korean-bbq-beef.jpg" },
  { "name": "Kung Pao Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kung-pao-chicken.jpg" },
  { "name": "Lamb Gyro", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lamb-gyro.jpg" },
  { "name": "Lasagna", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lasagna.jpg" },
  { "name": "Lean Beef (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lean-beef-cooked.jpg" },
  { "name": "Lemon", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lemon.jpg" },
  { "name": "Lemon Herb Chicken Plate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lemon-herb-chicken-plate.jpg" },
  { "name": "Lentil Buddha Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lentil-buddha-bowl.jpg" },
  { "name": "Lentil Soup", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lentil-soup.jpg" },
  { "name": "Lentil Tomato Soup", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lentil-tomato-soup.jpg" },
  { "name": "Lentils (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lentils-cooked.jpg" },
  { "name": "Lime", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/lime.jpg" },
  { "name": "Mac and Cheese", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mac-and-cheese.webp" },
  { "name": "Mango", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mango.jpg" },
  { "name": "Margherita Pizza", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/margherita-pizza.jpg" },
  { "name": "Mashed Potato", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mashed-potato.jpg" },
  { "name": "Mashed Potatoes with Gravy", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mashed-potatoes-with-gravy.jpg" },
  { "name": "Matcha Latte", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/matcha-latte.jpg" },
  { "name": "Matcha Yogurt Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/matcha-yogurt-bowl.jpg" },
  { "name": "Mayonnaise", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mayonnaise.jpg" },
  { "name": "Mediterranean Chickpea Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-chickpea-salad.jpg" },
  { "name": "Mediterranean Chickpea Stew", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-chickpea-stew.jpg" },
  { "name": "Mediterranean Grilled Salmon", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-grilled-salmon.jpg" },
  { "name": "Mediterranean Salmon Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-salmon-bowl.jpg" },
  { "name": "Mediterranean Tuna Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-tuna-bowl.jpg" },
  { "name": "Mediterranean Tuna Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mediterranean-tuna-salad.jpg" },
  { "name": "Milk (2%)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/milk-2.webp" },
  { "name": "Milk (whole)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/milk-whole.jpg" },
  { "name": "Milk Chocolate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/milk-chocolate.jpg" },
  { "name": "Milkshake (vanilla)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/milkshake-vanilla.jpg" },
  { "name": "Minestrone Soup", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/minestrone-soup.jpg" },
  { "name": "Miso Salmon Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/miso-salmon-bowl.jpg" },
  { "name": "Miso Soup", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/miso-soup.jpg" },
  { "name": "Mocha", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mocha.jpg" },
  { "name": "Mozzarella", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mozzarella.jpg" },
  { "name": "Muffin", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/muffin.jpg" },
  { "name": "Mushroom", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mushroom.jpg" },
  { "name": "Mushroom Barley Soup", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mushroom-barley-soup.jpg" },
  { "name": "Noodles with Chicken", "url": "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=1200&q=80" },
  { "name": "Oatmeal with Banana", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/oatmeal-with-banana.jpg" },
  { "name": "Oats (dry)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/oats-dry.jpg" },
  { "name": "Olive Oil", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/olive-oil.jpg" },
  { "name": "Omelette", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/omelette.jpg" },
  { "name": "Onion", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/onion.jpg" },
  { "name": "Orange", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/orange.webp" },
  { "name": "Orange Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/orange-chicken.jpg" },
  { "name": "Overnight Oats with Chia", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/overnight-oats-with-chia.jpg" },
  { "name": "Pad Thai", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pad-thai.jpg" },
  { "name": "Palak Paneer", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/palak-paneer.jpg" },
  { "name": "Pancakes", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pancakes.jpg" },
  { "name": "Paneer Tikka Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/paneer-tikka-bowl.jpg" },
  { "name": "Papaya", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mango.jpg" },
  { "name": "Parmesan", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/mozzarella.jpg" },
  { "name": "Pasta (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pasta-cooked.jpg" },
  { "name": "Pasta Primavera", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pasta-primavera.jpg" },
  { "name": "Peach", "url": "https://pub-aaa82e9851064d22b954c3ebbafc9ae6.r2.dev/legacy/masters/peach-tea-SdR1X5msJbMy5Mu8kDuag.jpg" },
  { "name": "Peanut Butter", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/peanut-butter.jpg" },
  { "name": "Peanut Butter Jelly Sandwich", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/peanut-butter-jelly-sandwich.jpg" },
  { "name": "Peanut Butter Oatmeal Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/peanut-butter-oatmeal-bowl.jpg" },
  { "name": "Pear", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pear.jpg" },
  { "name": "Peas", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/peas.jpg" },
  { "name": "Pepperoni Pizza", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pepperoni-pizza.png" },
  { "name": "Pesto Pasta", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pesto-pasta.jpg" },
  { "name": "Pho (beef)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pho-beef.jpg" },
  { "name": "Pineapple", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pineapple.jpg" },
  { "name": "Pistachios", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pistachios.webp" },
  { "name": "Pizza Cheese", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/margherita-pizza.jpg" },
  { "name": "Plum", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/plum.jpg" },
  { "name": "Poke Bowl (chicken)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/poke-bowl-chicken.jpg" },
  { "name": "Poke Bowl (salmon)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/poke-bowl-salmon.jpg" },
  { "name": "Poke Bowl (tuna)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/poke-bowl-tuna.jpg" },
  { "name": "Popcorn (air-popped)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/popcorn-air-popped.jpg" },
  { "name": "Pork Loin (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pork-loin-cooked.webp" },
  { "name": "Porridge (oatmeal milk)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/porridge-oatmeal-milk.jpg" },
  { "name": "Potato (boiled)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/potato-boiled.jpg" },
  { "name": "Potato Chips", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/potato-chips.jpg" },
  { "name": "Pozole", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pozole.jpg" },
  { "name": "Pretzels", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/pretzels.jpg" },
  { "name": "Protein Pancakes", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/protein-pancakes.jpg" },
  { "name": "Protein Powder", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/protein-powder.jpg" },
  { "name": "Protein Yogurt Parfait", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/protein-yogurt-parfait.jpg" },
  { "name": "Quinoa (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/quinoa-cooked.jpg" },
  { "name": "Quinoa Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/quinoa-salad.jpg" },
  { "name": "Quinoa Tabbouleh", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/quinoa-tabbouleh.jpg" },
  { "name": "Quinoa Veggie Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/quinoa-veggie-salad.jpg" },
  { "name": "Raisins", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/raisins.jpg" },
  { "name": "Rajma Rice Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/rajma-rice-bowl.jpg" },
  { "name": "Ramen (prepared)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/ramen-prepared.jpg" },
  { "name": "Red Curry Tofu", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/red-curry-tofu.jpg" },
  { "name": "Rice with Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/rice-with-chicken.jpg" },
  { "name": "Risotto", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/risotto.jpg" },
  { "name": "Roast Chicken with Potatoes", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/roast-chicken-with-potatoes.jpg" },
  { "name": "Roasted Chickpea Snack Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/roasted-chickpea-snack-bowl.jpg" },
  { "name": "Roasted Turkey Plate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/roasted-turkey-plate.jpg" },
  { "name": "Roasted Veggie Grain Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/roasted-veggie-grain-bowl.webp" },
  { "name": "Salmon (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-cooked.jpg" },
  { "name": "Salmon and Asparagus Plate", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-and-asparagus-plate.jpg" },
  { "name": "Salmon Avocado Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-avocado-bowl.jpg" },
  { "name": "Salmon Caesar Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-caesar-salad.jpg" },
  { "name": "Salmon Nigiri", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-nigiri.jpg" },
  { "name": "Salmon with Rice", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/salmon-with-rice.jpg" },
  { "name": "Sardine Rice Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sardine-rice-bowl.webp" },
  { "name": "Scrambled Eggs with Toast", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/scrambled-eggs-with-toast.jpg" },
  { "name": "Shakshuka", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/shakshuka.jpg" },
  { "name": "Shrimp (cooked)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/shrimp-cooked.jpg" },
  { "name": "Shrimp Burrito Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/shrimp-burrito-bowl.jpg" },
  { "name": "Simple Oven-Baked Sea Bass", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/simple-oven-baked-sea-bass.jpg" },
  { "name": "Skim Milk", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/skim-milk.jpg" },
  { "name": "Smoked Salmon Toast", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/smoked-salmon-toast.jpg" },
  { "name": "Smoothie (fruit)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/smoothie-fruit.jpg" },
  { "name": "Spaghetti Bolognese", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/spaghetti-bolognese.jpg" },
  { "name": "Spinach", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/spinach.jpg" },
  { "name": "Spinach Berry Salad", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/kale-chicken-salad.jpg" },
  { "name": "Spinach Shakshuka", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/spinach-shakshuka.jpg" },
  { "name": "Steak Burrito Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/steak-burrito-bowl.jpg" },
  { "name": "Steak with Rice", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/beef-bulgogi-bowl.webp" },
  { "name": "Strawberry", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/strawberry.jpg" },
  { "name": "Stuffed Bell Pepper", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/stuffed-zucchini-boats.jpg" },
  { "name": "Stuffed Zucchini Boats", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/stuffed-zucchini-boats.jpg" },
  { "name": "Sugar", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sugar.jpg" },
  { "name": "Sunflower Seeds", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sunflower-seeds.jpg" },
  { "name": "Sushi (mixed)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sushi-mixed.jpg" },
  { "name": "Sushi Roll (avocado)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sushi-roll-avocado.jpg" },
  { "name": "Sushi Roll (salmon)", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sushi-roll-salmon.jpg" },
  { "name": "Sweet and Sour Chicken", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sweet-and-sour-chicken.jpg" },
  { "name": "Sweet Potato", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/sweet-potato.webp" },
  { "name": "Tabbouleh", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/tabbouleh.jpg" },
  { "name": "Taco Beef", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/taco-beef.jpg" },
  { "name": "Tempeh", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/tempeh.jpg" },
  { "name": "Teriyaki Chicken Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/teriyaki-chicken-bowl.jpg" },
  { "name": "Teriyaki Tofu Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/teriyaki-tofu-bowl.jpg" },
  { "name": "Thai Peanut Chicken Bowl", "url": "https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/thai-peanut-chicken-bowl.png" }
]$$::jsonb
  )
),
rows_from_json as (
  select
    trim(x.name) as name,
    trim(x.url) as url
  from payload p
  cross join lateral jsonb_to_recordset(p.raw_json) as x(name text, url text)
  where coalesce(trim(x.name), '') <> ''
    and coalesce(trim(x.url), '') <> ''
),
deduped_urls as (
  select distinct name, url
  from rows_from_json
),
ranked as (
  select
    name,
    url,
    row_number() over (
      partition by name
      order by
        case
          when url like 'https://qgnzcqwonmlijdvnbqjd.supabase.co/storage/v1/object/public/Meals/%' then 0
          else 1
        end,
        url
    ) as rn
  from deduped_urls
),
per_food as (
  select
    name,
    max(url) filter (where rn = 1) as primary_url,
    jsonb_agg(url order by rn, url) as all_urls
  from ranked
  group by name
)
update public.foods f
set
  image_url = p.primary_url,
  image_urls = p.all_urls,
  photo_source = coalesce(f.photo_source, 'user_import'),
  image_review_status = coalesce(f.image_review_status, 'approved')
from per_food p
where f.name = p.name;

